### ISSUE TITLE
No longer working on HPOS enabled stores

### ISSUE THREAD

**Issue by DarkAllMan** [kinging123/woo-shipping-class-filter#2]
After enabling HPOS, the filter dropdown is no longer visible.

**Comment by reuvenkarasik** [comment]
This plugin is not actively maintained, so enabling breaking changes like HPOS can definitely break some features. 
If you need to use the plugin, yet still must enable HPOS, I recommend hiring a developer to adapt the plugin for the new API. 
Any pull requests about this would be highly appreciated!
